### ISSUE TITLE
josm plugin freezes

### ISSUE THREAD

**Issue by Jakkajakka** [JOSM/Mapillary#175]
When activating or deactivating mapillary layer to see the green dots/view josm freezes for about 10 sec then can work again . Then activating or deactivating again about 10 sec on hold.... what wrong even after a fresh reboot immediately the same issue ... Who knows what happening ?

**Comment by tsmock** [comment]
A couple of questions:
1) Can you paste a JOSM status report?
2) The current "latest" version of the plugin is v1.5.36.3. I've had to a lot of tiny releases recently due to a bunch of issues that didn't show up during testing (it "worked" on my machine, as in I am often unable to reproduce locally, but the stack traces give me enough information to fix the problem)

**Comment by Jakkajakka** [comment]
Dowloaded last + Mapillary (1.5.36.3) still about 5 sec reaction time

[status_report.txt](https://github.com/JOSM/Mapillary/files/5821145/status_report.txt)

**Comment by tsmock** [comment]
I'm essentially rewriting the render code and download code. This will (hopefully) fix the problem.

**Comment by dex2000** [comment]
Same here since january i think.
20 seconds freeze for deactivating the layer and 20 too for activating again.

    + Mapillary (1.5.37.6)
    Identification: JOSM/1.5 (17833 de) Windows 7 64-Bit
    
no errors or something in the log

**Comment by tsmock** [comment]
Like I noted above, I'm rewriting the render and download code. See https://gitlab.com/smocktaylor/Mapillary/-/merge_requests/153 (depends upon JOSM ticket [#17177](https://josm.openstreetmap.de/ticket/17177), see https://gitlab.com/smocktaylor/josm/-/merge_requests/2 for my current progress on #17177).
