### ISSUE TITLE
Render hung up sequences

### ISSUE THREAD

**Issue by masterofnoroad** [JOSM/Mapillary#178]
Some time ago (mid-2020) the bot blocking non-street level imagery was introduced. Unfortunatelly it is blocking all pictures in the sequence from appearing on the map. Even if only one picture there is faulty.

The problem was sygnalised to mapillary for some time, they finally acknowledged it and started to work on a solution...but that was two weeks ago and the sequences keep missing. It is quite hard to get any feedback from them.

The discussion on mapillary forum is here:
https://forum.mapillary.com/t/missing-parts-of-the-sequences/4588

But the sequences can be seen and accesed.
How? Through the ID editor. Just open the place and they will show up there as separate photos without connecting sequence line.  And then it is possible to open each picture in mapillary webpage, but the sequence controls are inactive and editor cannot be accessed either. Navigation arrows are working and sometimes it is possible to jump to that photo from the other good one.

Here are the examples, link to the picture and screen from the ID editor:

[https://www.mapillary.com/map/im/7ntCVhWQ1b3SOkO81ORGZx](https://www.mapillary.com/map/im/7ntCVhWQ1b3SOkO81ORGZx)
<img width="762" alt="imagen" src="https://user-images.githubusercontent.com/72669347/113850620-f4a2cd80-979a-11eb-8c16-fff164e43f58.png">

It means, the pictures are there. They can be accesed (but with limited functionality). If ID can do this, is there an option to show them also in JOSM?

**Comment by tsmock** [comment]
If a sequence is not visible in the web app, there is a high chance that it will not be visible in iD and JOSM in the future (the API is changing, see https://blog.mapillary.com/update/2021/03/03/preparing-for-the-new-mapillary-api.html ).

I can repro in JOSM, _but_ I'm not going to try and fix it, due to the API change (all I'll have access to is the same vector tiles that Mapillary uses on their web page).

That being said, it is _possible_ that it may be visible, since the consumer (aka the plugin) are expected to do the filtering.
