### ISSUE TITLE
Photo contributor username is no longer displayed, user filter doesn't work.

### ISSUE THREAD

**Issue by govvin** [JOSM/Mapillary#181]
I'm using JOSM v17915, and the Mapillary plugin to v 2.0.0.alpha.5

In this version of the Mapillary plugin, the name of the contributor is no longer displayed on top of the Mapillary image window, nor in the Image info window. The image window states the user is "unknown user."

![image](https://user-images.githubusercontent.com/5821688/120253645-7ce4b100-c2ba-11eb-923f-9b7d0330b124.png)

Even if I know the username of the contributor, and attempt to filter out images based on the username, the user filter doesn't work as expected, and no sequence is displayed at all.

**Comment by tsmock** [comment]
I don't have a call I can make to API v4 yet for users. I'm waiting for the official release of the v4 API. If there is an API to get a user from a user id (v3 tiles give me a userkey, *not* a user name), that will be fixed. Otherwise, it will be removed.

I haven't done either yet since I don't know what the full v4 API looks like.

**Comment by tsmock** [comment]
Just to avoid confusion, I've disabled the user input field and added a tooltip. Along with text in the field to make it clear that it is disabled.

**Comment by govvin** [comment]
Thanks @tsmock

**Comment by tsmock** [comment]
I'm closing this since the v4 api doesn't return any user fields, and I've removed the user filter in the v4 API code.
