### ISSUE TITLE
How can I install a previous version?

### ISSUE THREAD

**Issue by angoca** [JOSM/Mapillary#188]
I would like to know if I can install a previous version of this plugin in JOSM?
This due to errors in the most recent version

**Comment by GhostFoxSledgehammer** [comment]
I guess you need to manually download the version you want to install and then follow the step given in the [wiki](https://wiki.openstreetmap.org/wiki/JOSM/Plugins).

**Comment by tsmock** [comment]
This may not help your use case:
* #186 : This is due to a change in JOSM. I've fixed this, now that someone (you) has reported it.
* #187 : This is due to a change in the Mapillary OAuth flow. It is something that I've been working on fixing.

Both of your reported issues are due to changes not in the Mapillary plugin, so downgrading will not fix your issues.
Note: For faster responses, please use the JOSM bug tracker -- I get emails from that one. I don't get emails from the GitHub bug tracker. Alternatively, you can @ mention me as well.

**Comment by tsmock** [comment]
@angoca : I've fixed both of your reported issues. If you encounter more bugs, please let me know.
