### ISSUE TITLE
select wrong picture by click on a point on the map

### ISSUE THREAD

**Issue by hakuchi** [JOSM/Mapillary#191]
The today newly installed end never used before plugin show the wrong picture if i click on a point in Josm.

Example:
I click on a point in Josm to receive following picture:
https://www.mapillary.com/map/im/541235463542548
Josm open the following image:
https://www.mapillary.com/map/im/2923192274625487

these pictures are not from the same sequence and not from the same user.

I am using Josm 18327 and plugin 2 alpha 49

**Comment by tsmock** [comment]
Thank you for the bug report.

I haven't been able to reproduce. Can you try again?

I'm going to include the standard request for more information from JOSM Trac, as it is _possible_ that the problem may be configuration specific.

---

Thanks for your report, however your ticket is incomplete and therefore not helpful in its current form.

Please add all needed information according to this list:

* The required parts of the Status Report from your JOSM.
  * Please, use Report Bug from Help menu and copy & paste. 
* Describe what behaviour you expected.
* Describe what did happen instead.
* Describe if and how the issue is reproducible.
* Add any relevant information like error messages or screenshots. 

To ensure that all technical relevant information is contained, create new tickets by clicking in JOSMs Main Menu on Help → Report Bug.

**Comment by hakuchi** [comment]
I fixed by my self.
I deleted complete data from Josm from my PC.
There was something corupted in my "preferences.xml" file, so I had to set all new after clean installation of JOSM.

Now Mapillary and all other stuff is working fine.

**Comment by tsmock** [comment]
>  There was something corupted in my "preferences.xml" file, so I had to set all new after clean installation of JOSM.
I'm sorry to hear that. :(

I (personally) hate setting up my JOSM environment (it gets reset all the time, due to the way tests get run).
