### ISSUE TITLE
"Unsupported get request" when clicking on a detected point object

### ISSUE THREAD

**Issue by ireun** [JOSM/Mapillary#197]
Hi!

I'm encountering following error after clicking on a detected PointObject (this includes traffic signs):

`E: {"error":{"message":"Unsupported get request. Object with ID '97' does not exist, cannot be loaded due to missing permissions, or does not support this operation","type":"MLYApiException","code":100,"error_subcode":33,"fbtrace_id":"APMZFBxB5wNOzE8znAEo-a5"}}`

![image](https://user-images.githubusercontent.com/695818/178010483-9f973e60-4122-498a-bfec-2d9b69c070a2.png)

**Comment by tsmock** [comment]
Where? (a link to a nearby OSM object will work).

I don't have time to spin up Mapillary right now, but it _was_ working last time I checked.

**Comment by ireun** [comment]
Let's try that: https://streamable.com/z8bfi5

**Comment by tsmock** [comment]
I hate how mapillary does their ids. They really should use the `id` in the tile instead of setting a key to the `id`. 
From the MVT spec, "[a] feature MAY contain an id field. If a feature has an id field, the value of the id SHOULD be unique among the features of the parent layer." Since they have an `id` field, they really ought to use that to set the `id` of the feature object. At one point, I believe those were unset, and I was kind of depending upon that. Anyway, I'll get a fix out today.
