### ISSUE TITLE
Add a Mapillary tag to an object

### ISSUE THREAD

**Issue by overflorian** [JOSM/Mapillary#33]
Hi,
I suggest you add a button to add a "mapillary=*" tag to an object.

Use case: 
1. load OSM data and display the Mapillary layer
2. Select an OSM object. Its attributes are then displayed in the "attributes" window
3. Select a Mapillary picture. Its thumbnail is then displayed in the "mapillary picture" window
4. Click on "Add the tag" button in the Mapillary window
5. The Mapillary tag is added to the OSM object with its reference

Example : 
1. Load data in JOSM
2. Select the node [https://www.openstreetmap.org/node/3250355388](https://www.openstreetmap.org/node/3250355388)
3. Select the picture [https://www.mapillary.com/app/?focus=photo&pKey=JeKD581InP4VzrvRzk2SPA](https://www.mapillary.com/app/?focus=photo&pKey=JeKD581InP4VzrvRzk2SPA)
4. Click on the button "add the tag"
5. Here you go ! The "mapillary=JeKD581InP4VzrvRzk2SPA" tag is added to the node

This would be way much easier to add a Mapillary tags with this solution.
Nowadays I click on "view on the website", copy the part of the URL in my browser, close the tab, come back to JOSM, create a new "Mapillary" tag, paste the reference number.
It's such a pain when you tag dozens of pictures as I do.

There is currently about [6000 objects tagged with this tag](https://taginfo.openstreetmap.org/search?q=mapillary) and I am sure such a solution could boost it much more.

This tag is now essential on the projects I currently run. I have to PROVE that the data on-site is the one I created. The picture is that proof.

Check out for example the map I made of the [brand new recycling containers in Paris](https://www.rudomap.xyz/t/4888d9-Bornes_Trilib)
Every container you select displays a Mapillary picture of it.
I explain my project in [a blog post](http://florian.lainez.fr/le-jour-ou-jai-fait-les-poubelles) (sorry only in French).

Again, you already know it guys: I am a big fan of your plug-in and use it almost every day. Keep going !
Your friend from Paris, Florian

**Comment by floscher** [comment]
Hi, thank you for the suggestion. I will look into it and see what I can improve in this regard, there are already some ideas coming to my mind.

But meanwhile you can already ease your workflow with any current version of the plugin (current meaning v1.0 or later :wink: ). If you click the link to the website with the right mouse button you get a context menu with the options to copy the image key or the whole tag into your clipboard.
Simply select „Copy mapillary tag“, select the table containing the tags for an OSM-object and press Ctrl+V to paste the tag.

To be honest, I also didn't know about that feature, I discovered it only today when digging in that part of the source code. It's currently quite well hidden, so probably only "insiders" get the idea to right click that link. :wink:

Your friend from southern Germany, Florian :wave:

**Comment by overflorian** [comment]
"It's not a bug, it's a feature" !!
I love you hack, it's already saving me a lot of time.

I look forward an even quicker solution, thanks Florian

**Comment by floscher** [comment]
Hi, I've now put up a pre-release containing such a button that can put a mapillary tag onto the currently selected OSM object.
You can try it out from the [release page of v1.4.0-beta](https://github.com/JOSM/Mapillary/releases/tag/v1.4.0-beta). Simply download the file `Mapillary.jar` and put it into your local directory `~/.josm/plugins` (replace the current version of the plugin, that resides there).

**Comment by overflorian** [comment]
Hi, thanks for this, it definitely does the job. I am using it from nowadays.

Nevertheless think that it takes a lot of space on the screen. As you can see it's a bit overcrowded: ![capture](https://cloud.githubusercontent.com/assets/11553211/22553106/d1ea746a-e95b-11e6-8828-190311ca1c5d.PNG)
This is a real concern as the picture is already a small thumbnail.

I suggest you embed these buttons directly in the picture's window.
As it's already busy I wonder if you could reduce the size of existing buttons, for example "previous picture" and "next picture" could become little arrows such as < and >
Also I wonder what are the "go to blue" and "go to red" buttons that I never used.

For me, but it's only my point of view, I would have these 4 buttons:
<  ;  Add Mapillary tag ; View in browser ; >

Also I don't really see the value of displaying the sequence key.
If you really want to keep the image key and the "copy key" button, I suggest you put them on the same line.

Hope it helps, regards

**Comment by floscher** [comment]
Thank you for that feedback. I'll definitely implement at least parts of it.
For example I didn't so much realize the space problem, because I used a high resolution monitor when developing. So definitely the (admittedly extra large) buttons will become smaller for the final 1.4.0 release.

One thing you could do to make the image larger is to click the pin needle in the top right corner of the image panel (next to the ×). This undocks the image and you can move it freely around and resize it to your liking. To dock it again, simply close the window again.

Maybe the "View in browser" link might indeed move back to the image display, from a users point of view that would probably make more sense. When reading your feedback I realized, I grouped these buttons, because it makes sense from the developer's point of view (all three actions take the image key and do something with it).
I'll probably leave the "Add Mapillary tag" button in the new panel, so that you see which key you are adding to the OSM object.

Changing the other buttons below the image might be an option for the future, although not for the next release. These are the standard buttons provided by JOSM, the same ones as used in e.g. the attributes panel.

Regarding the blue and red button, that's quite easy to explain:
![grafik](https://cloud.githubusercontent.com/assets/3904348/22556185/926423d0-e966-11e6-8bc4-1d77399a6e70.png)
The "next" and "previous" button switch to the neighbouring images in the same sequence, whereas "red" switches to the nearest image from a different sequence and "blue" switches to the nearest image from neither of the two sequences.
This is also indicated by the red and blue lines in the MapView.

Thank you!

**Comment by overflorian** [comment]
Thank you for this Florian. I look forward for the final UI and will definitely give you my feedback.

> One thing you could do to make the image larger is to click the pin needle in the top right corner of the image panel (next to the ×). This undocks the image and you can move it freely around and resize it to your liking. To dock it again, simply close the window again.

Yes I already know that. But even when unpinned, a window still overlaps my screen and hides a part of the map. Therefore I prefer to let it docked on the right panel.

Regards

**Comment by PolyglotOpenstreetmap** [comment]
When I was mentoring the developer who wrote the initial version, I asked
him to make the location of the buttons configurable. I prefer to have them
on top, as I can then move the window using the blue bar a bit more out of
the way and at the same time still see part of the picture. Using the
scroll mouse button it's possible to zoom in and out on the picture, so no
need to move the window all the time. Unfortunately this feature was lost
at some point.

Concerning the buttons. There is a mode to make the pictures 'play' like
they do on the website. It's another feature that got hidden and is
therefore probably never used. It would be nice if there were a button to
enable this mode, replacing the usual buttons with forward/back and return
to normal mode buttons.

Florian, I'm proposing to have the Mapillary plugin as part of the GSoC
once again. Do you see things a student can improve on it, and would you,
ideally, be prepared to co-mentor it? Do you think it makes sense to also
incorporate pictures from OpenStreetCam? I know there is a separate plugin
for it, haven't used it yet, unfortunately.

 It's not the only thing I'd like to see improved. More work can be done on
the project from last year, adding foot and bicycle routes to the public
transport plugin and then there is the RoadSigns plugin, which bothers me
already for a few years now.

Cheers,

Polyglot

2017-02-03 23:44 GMT+01:00 Overflorian <notifications@github.com>:

**Comment by floscher** [comment]
@overflorian Thanks for [tweeting about this](https://twitter.com/overflorian/status/827164409231323136)!

@PolyglotOpenstreetmap Sure, I'd be available for co-mentoring a GSoC project. Probably in the end phase of coding (end of July and first half of August) I'll probably have not much spare time, but for the rest of the time I'd probably find time to help.

I created a [project for gathering ideas](https://github.com/JOSM/Mapillary/projects/2), for reference this is the official project idea page for all project ideas related to OSM: https://wiki.openstreetmap.org/wiki/Google_Summer_of_Code/2017/Project_Ideas .

Concerning new features: Finally bringing traffic signs to the plugin would be one task (I promised that in the past, but never got around finishing it), or usig the vector tiles instead of the API for downloading sequences.
I think the RoadSigns plugin would be a better fit to integrate with the mapillary plugin. Also displaying images from OpenStreetCam might confuse some users to which images are from which site, especially when they already have a separate plugin. And probably more code would need adaption, because the plugin is currently tailored to use only this one image source.

And about the buttons, yes I removed the option to put them to the top (deliberately :hushed:), but if we are going to replace them anyway, what about something that looks like on the  Mapillary website? At the top center overlayed over the image?
