### ISSUE TITLE
Import Pictures error using Mapillary v 1.3.2

### ISSUE THREAD

**Issue by govvin** [JOSM/Mapillary#36]
I'm using JOSM version 11526 and is unsuccessful with import a photo using JOSM+Mapillary. I uploaded the same photo using the Mapillary web app, it works fine.

It would be nice to be able to keep these tasks within JOSM, especially if I'm already using it.

![img_20161220_104737](https://cloud.githubusercontent.com/assets/5821688/23053146/3a012fa0-f512-11e6-84a9-bda10cf6aeca.jpg)

JOSM error debug message:
[error_text_josm_mapillary.txt](https://github.com/JOSM/Mapillary/files/782352/error_text_josm_mapillary.txt)

**Comment by floscher** [comment]
Thank you for reporting, this was not an issue with the Mapillary plugin itself. The plugin `apache-commons` was changed incompatibly since the last release, which caused the Mapillary plugin to fail.
I simply recompiled the version v1.3.2 of the plugin against the latest version of the `apache-commons` plugin.
So if you update your JOSM plugins (go to the JOSM preferences, in the Plugins section there is a button to update the plugins at the bottom) and restart JOSM, you should be able to import images again.
