### ISSUE TITLE
NumberFormatException when parsing json with v1.5.9

### ISSUE THREAD

**Issue by don-vip** [JOSM/Mapillary#71]
It seems there's a big problem in v1.5.9, we're spammed with bug reports:

https://josm.openstreetmap.de/ticket/15682
https://josm.openstreetmap.de/ticket/15684
https://josm.openstreetmap.de/ticket/15686

**Comment by floscher** [comment]
Probably this is caused by the Mapillary API returning unexpected values in the JSON. I haven't changed those classes recently, in which the exception originates.
cc @peterneubauer: Any changes to the APIv3 output that could have caused this.

But we should do something to handle the exception more gracefully. Currently `JsonException`s are catched and a notification appears. I think I'll add `NumberFormatException` to the catch clause and handle these the same way.
In the next days I'll release a fix of some kind in any case, to handle this more gracefully.

If I see this correctly, the `JsonReader` from Glassfish JSON (included in the JOSM *.jar) is throwing this `NumberFormatException` when it should only throw a `JsonException`, `JsonParsingException` or `IllegalStateException` according to the [documentation](https://javadoc.io/doc/org.glassfish/javax.json/1.1). @don-vip Could maybe updating that dependency help and/or filing a bug report for Glassfish JSON?

**Comment by don-vip** [comment]
Yes we could update. I was not sure because last time I checked we couldn't. It was in the Java 7 days, and the version 1.1 requires Java 8. Not a problem anymore.

**Comment by don-vip** [comment]
Done: https://josm.openstreetmap.de/changeset/13231/josm

**Comment by peterneubauer** [comment]
Thanks Florian for the fix!
