### ISSUE TITLE
Pictures in the wrong place in JOSM

### ISSUE THREAD

**Issue by naomap** [JOSM/Mapillary#81]
This picture on Mapillary looks at the right place on the map: https://www.mapillary.com/app/?focus=map&pKey=BE-9uFedYZxrbgIVWBVwCg&lat=48.794617310756166&lng=2.331230420550696&z=17&menu=false

However looking at the same location in JOSM, the same picture is located at this place where the surroundings are totally different : https://www.openstreetmap.org/#map=18/48.79348/2.33458

This is the same sequence about 50 pictures down the road, this is very confusing !

**Comment by tsmock** [comment]
I have confirmed that this is still an issue.

Loading via remote control does _not_ show the problem, although there is a slightly different problem.

`curl 'http://127.0.0.1:8111/photo?photo=Mapillary/BE-9uFedYZxrbgIVWBVwCg'`

Note: Remote Control support is not in a currently released version of the Mapillary plugin.

**Comment by tsmock** [comment]
OK. It looks like a Mapillary platform issue. I've informed them about this particular issue.

**Comment by naomap** [comment]
Thank you for looking into this issue. I am surprised you closed it though : is it fixed, or planned to be fixed ? How will I get informed of any progress ?

**Comment by tsmock** [comment]
I primarily closed since it is not something I can affect, or can be fixed in the plugin. The best I can do is inform them of the issue (this is _not_ just a JOSM  Mapillary plugin issue). I've been told they filed an internal bug for it. I may end up writing a script to find _all_ similar issues (all I have to do is compare the returns from the `/images` endpoint and the `/sequences` endpoint).

While I can _technically_ do something about it (i.e., for every image in every sequence, make a call to `/images`, I'd prefer to avoid that -- network calls already aren't the quickest thing for the Mapillary plugin, and I don't want to slow it down more). This is really something that needs to be fixed on the Mapillary server side.

It does look like your specific sequence problem has been fixed though.

In any case, what it looked like from the API response side is that the image keys were being returned out of order for a sequence, while the geometry points were being returned in order.

**Comment by naomap** [comment]
I see... ! Sorry I didn't realize (or forgot) I reported this against the JOSM/Mapillary plugin. Indeed since this is an issue with the Mapillary platform this should be fixed there rather than adding some hackery on the JOSM side.
Thanks, Antoine.

**Comment by tsmock** [comment]
No problem. I don't mind getting bug reports like this (since they _might_ be an issue with the JOSM plugin). It just happened that this case also affected the website. I can always forward the bug to my contact in Mapillary if I do find that it is a general server side issue instead of a JOSM specific issue.
